### ISSUE TITLE
For Fibonacci Lab

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/ruby-vs-js-array-methods#1]
Clarify it's the first 10 numbers for all bullets via @gaand

**Comment by jrhorn424** [comment]
@gaand addressed here: https://github.com/ga-wdi-boston/ruby-vs-js-array-methods/commit/5adbf7a0a69b0b84cf397f16c2aeb887996eb229#diff-04c6e90faac2675aa89e2176d2eec7d8L49
